### ISSUE TITLE
sintesis

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-christopheremv#1]
[sintasis calidad de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-christopheremv/files/9647046/sintasis.calidad.de.software.pdf)

**Comment by josealfredo79** [comment]
No hay calificacion...

**Comment by josealfredo79** [comment]
Calificación 17

**Comment by josealfredo79** [comment]
Bien hecho y revisado
